### PR TITLE
Support Contao 4.4.

### PR DESCRIPTION
**Pull request by dmolineus**
This PR will allow to install boxes4ward in Contao 4. I set requirement to 4.4 as I only tested it in C4.4

### CODE REVIEW

**Comment by cliffparnitzky** [comment]
@psi-4ward This PR was merged but never tagged. Please create a tag. Thanks.

**Comment by baumannsven** [comment]
@cliffparnitzky Please wait a moment. In January next I rebuild this package

**Comment by psi-4ward** [comment]
Yes cause I've not done any tests. If you could tell me everything works I'll create a tag for it

**Comment by cliffparnitzky** [comment]
I send this to the community ... there should be some interested people.

**Comment by m-werk** [comment]
I tested the module. Under Contao 4.6.11 it works correctly

**Comment by psi-4ward** [comment]
Created a new tag. Sorry for the delay

**Pull request merged**
